### ISSUE TITLE
General CI Failure August 2023

### ISSUE THREAD

**Issue by traversaro** [robotology/robometry#183]
https://github.com/robotology/robometry/actions/runs/5921165075
https://github.com/robotology/robometry/actions/runs/5921143453

**Comment by Nicogene** [comment]
Chatting /w @traversaro it came out this is due to a regression of this PR:

- https://github.com/robotology/ycm/pull/422

To fix it we could either:
- port the test to catch3
- Force the usage of ycm 0.14.0 in the CI
